-- ============================================================================
-- 🐘 Neon PostgreSQL Setup & Seed Script (Standard SQL Integer Identity)
-- AI Predictive Maintenance System
-- ============================================================================

-- 1. Create sensor_readings table with INTEGER IDENTITY
CREATE TABLE IF NOT EXISTS sensor_readings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id VARCHAR(20) NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    vibration DOUBLE PRECISION NOT NULL,
    current DOUBLE PRECISION NOT NULL,
    rpm INTEGER NOT NULL,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_machine_time 
ON sensor_readings (machine_id, recorded_at DESC);


-- 2. Create alert_log table with INTEGER IDENTITY
CREATE TABLE IF NOT EXISTS alert_log (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id VARCHAR(20) NOT NULL,
    risk_percent DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL,
    recipients TEXT NOT NULL,
    email_status VARCHAR(20) NOT NULL,
    error_message TEXT,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alert_time 
ON alert_log (sent_at DESC);


-- ============================================================================
-- 3. Initial Seed Data (Telemetry Streams for M01, M02, M03)
-- ============================================================================

-- Machine M01 (Normal Operating State)
INSERT INTO sensor_readings (machine_id, temperature, vibration, current, rpm, recorded_at) VALUES
('M01', 58.4, 1.85, 4.80, 1620, NOW() - INTERVAL '15 minutes'),
('M01', 59.1, 1.90, 4.95, 1610, NOW() - INTERVAL '12 minutes'),
('M01', 60.3, 1.82, 5.10, 1630, NOW() - INTERVAL '9 minutes'),
('M01', 58.9, 1.88, 4.90, 1625, NOW() - INTERVAL '6 minutes'),
('M01', 61.2, 1.95, 5.20, 1615, NOW() - INTERVAL '3 minutes'),
('M01', 59.8, 1.87, 5.05, 1640, NOW());

-- Machine M02 (Elevated Warning State)
INSERT INTO sensor_readings (machine_id, temperature, vibration, current, rpm, recorded_at) VALUES
('M02', 68.5, 2.80, 6.20, 1520, NOW() - INTERVAL '15 minutes'),
('M02', 72.1, 3.10, 6.80, 1490, NOW() - INTERVAL '12 minutes'),
('M02', 75.4, 3.45, 7.10, 1470, NOW() - INTERVAL '9 minutes'),
('M02', 78.2, 3.60, 7.40, 1450, NOW() - INTERVAL '6 minutes'),
('M02', 81.0, 3.90, 7.80, 1420, NOW() - INTERVAL '3 minutes'),
('M02', 82.5, 4.10, 8.10, 1390, NOW());

-- Machine M03 (High Failure Risk Anomaly)
INSERT INTO sensor_readings (machine_id, temperature, vibration, current, rpm, recorded_at) VALUES
('M03', 75.0, 3.20, 6.90, 1500, NOW() - INTERVAL '15 minutes'),
('M03', 82.3, 4.50, 8.40, 1380, NOW() - INTERVAL '12 minutes'),
('M03', 88.7, 5.20, 9.60, 1250, NOW() - INTERVAL '9 minutes'),
('M03', 92.4, 5.80, 10.30, 1120, NOW() - INTERVAL '6 minutes'),
('M03', 95.1, 6.40, 11.10, 1040, NOW() - INTERVAL '3 minutes'),
('M03', 96.8, 6.75, 11.80, 980, NOW());


-- ============================================================================
-- 4. Initial Alert History Log
-- ============================================================================

INSERT INTO alert_log (machine_id, risk_percent, status, recipients, email_status, error_message, sent_at) VALUES
('M03', 98.5, 'HIGH FAILURE RISK', 'abhishekdhokane143@gmail.com,udayrajput41153@gmail.com', 'sent', NULL, NOW() - INTERVAL '10 minutes'),
('M02', 74.2, 'WARNING', 'abhishekdhokane143@gmail.com,udayrajput41153@gmail.com', 'sent', NULL, NOW() - INTERVAL '45 minutes'),
('M01-TEST', 92.5, 'HIGH FAILURE RISK (TEST)', 'abhishekdhokane143@gmail.com,udayrajput41153@gmail.com', 'sent', NULL, NOW() - INTERVAL '2 hours');
