"""
PostgreSQL database layer for AI Predictive Maintenance System.
Supports both direct DATABASE_URL (e.g., Render/Neon/Supabase) and discrete DB_* parameters.
"""
import psycopg2
from contextlib import contextmanager
from typing import List, Optional, Dict, Any
from app.config import DATABASE_URL, DB_CONFIG


def get_connection():
    """Create a new database connection with appropriate SSL and URL handling."""
    if DATABASE_URL:
        dsn = DATABASE_URL
        # Render provides postgres://, psycopg2 works with postgresql:// or postgres://
        if dsn.startswith("postgres://"):
            dsn = "postgresql://" + dsn[len("postgres://"):]
        # If cloud postgres, enforce sslmode require if not already present
        if "sslmode=" not in dsn and "localhost" not in dsn and "127.0.0.1" not in dsn:
            sep = "&" if "?" in dsn else "?"
            dsn = f"{dsn}{sep}sslmode=require"
        return psycopg2.connect(dsn)
    else:
        return psycopg2.connect(**DB_CONFIG)


@contextmanager
def get_db():
    """Context manager for safely executing database transactions."""
    conn = get_connection()
    try:
        yield conn
    finally:
        conn.close()


def ensure_schema():
    """Create tables and indexes if they do not exist. Safe to run repeatedly."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS sensor_readings(
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    machine_id VARCHAR(20) NOT NULL,
                    temperature DOUBLE PRECISION NOT NULL,
                    vibration DOUBLE PRECISION NOT NULL,
                    current DOUBLE PRECISION NOT NULL,
                    rpm INTEGER NOT NULL,
                    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_machine_time
                ON sensor_readings(machine_id, recorded_at DESC);
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS alert_log(
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    machine_id VARCHAR(20) NOT NULL,
                    risk_percent DOUBLE PRECISION NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    recipients TEXT NOT NULL,
                    email_status VARCHAR(20) NOT NULL,
                    error_message TEXT,
                    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_alert_time
                ON alert_log(sent_at DESC);
            """)
            conn.commit()


def insert_reading(machine_id: str, temperature: float, vibration: float, current: float, rpm: int):
    """Insert a single sensor reading."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO sensor_readings(machine_id, temperature, vibration, current, rpm)
                VALUES(%s, %s, %s, %s, %s)
                RETURNING id, recorded_at;
            """, (machine_id, temperature, vibration, current, rpm))
            row = cur.fetchone()
            conn.commit()
            return {"id": row[0], "recorded_at": row[1]}


def latest() -> List[Dict[str, Any]]:
    """Return the most recent sensor reading for each monitored machine."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT DISTINCT ON(machine_id) 
                    machine_id, temperature, vibration, current, rpm, recorded_at
                FROM sensor_readings
                ORDER BY machine_id, recorded_at DESC;
            """)
            rows = cur.fetchall()
            return [
                {
                    "machine_id": r[0],
                    "temperature": r[1],
                    "vibration": r[2],
                    "current": r[3],
                    "rpm": r[4],
                    "recorded_at": r[5],
                }
                for r in rows
            ]


def history(machine_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Return historical readings for a given machine in chronological order."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT temperature, vibration, current, rpm, recorded_at
                FROM sensor_readings
                WHERE machine_id = %s
                ORDER BY recorded_at DESC
                LIMIT %s;
            """, (machine_id, limit))
            rows = cur.fetchall()
            # Return in chronological order (oldest to newest) for charting
            return [
                {
                    "temperature": r[0],
                    "vibration": r[1],
                    "current": r[2],
                    "rpm": r[3],
                    "recorded_at": r[4],
                }
                for r in reversed(rows)
            ]


def last_alert_time(machine_id: str):
    """Return the timestamp of the most recent alert sent for this machine, or None."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT sent_at FROM alert_log 
                WHERE machine_id = %s AND email_status = 'sent'
                ORDER BY sent_at DESC LIMIT 1;
            """, (machine_id,))
            row = cur.fetchone()
            return row[0] if row else None


def log_alert(machine_id: str, risk_percent: float, status: str, recipients: List[str], email_status: str, error_message: Optional[str] = None):
    """Record an alert attempt into the alert_log table."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO alert_log(machine_id, risk_percent, status, recipients, email_status, error_message)
                VALUES(%s, %s, %s, %s, %s, %s);
            """, (machine_id, risk_percent, status, ",".join(recipients), email_status, error_message))
            conn.commit()


def recent_alerts(limit: int = 20) -> List[Dict[str, Any]]:
    """Return the most recent alert log records."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT id, machine_id, risk_percent, status, recipients, email_status, error_message, sent_at
                FROM alert_log
                ORDER BY sent_at DESC
                LIMIT %s;
            """, (limit,))
            rows = cur.fetchall()
            return [
                {
                    "id": r[0],
                    "machine_id": r[1],
                    "risk_percent": r[2],
                    "status": r[3],
                    "recipients": [rec.strip() for rec in r[4].split(",") if rec.strip()],
                    "email_status": r[5],
                    "error_message": r[6],
                    "sent_at": r[7],
                }
                for r in rows
            ]


def get_stats() -> Dict[str, Any]:
    """Return high level telemetry and system stats."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM sensor_readings;")
            total_readings = cur.fetchone()[0]
            cur.execute("SELECT COUNT(*) FROM alert_log WHERE email_status = 'sent';")
            total_alerts_sent = cur.fetchone()[0]
            return {
                "total_readings": total_readings,
                "total_alerts_sent": total_alerts_sent,
            }
